namespace ThemeEngine.Generators;

public class BluetoothScriptGenerator : IGenerator
{
    public string Name => "Bluetooth Script";
    public string OutputPath => ".config/hypr/scripts/bluetooth-status.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var sep = theme.Waybar.Separator;

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# Bluetooth status for waybar custom module

ICON=$'\uf294'
SEP="<span color='{{c.Accent1}}'>{{sep}}</span>"

powered=$(bluetoothctl show 2>/dev/null | grep -c "Powered: yes")
if [[ "$powered" -eq 0 ]]; then
    printf '{"text": "%s off %s", "tooltip": "Bluetooth off", "class": "off"}\n' "$ICON" "$SEP"
    exit 0
fi

connected=$(bluetoothctl devices Connected 2>/dev/null)
if [[ -n "$connected" ]]; then
    device_name=$(echo "$connected" | head -1 | cut -d' ' -f3-)
    count=$(echo "$connected" | wc -l)
    if [[ "$count" -gt 1 ]]; then
        printf '{"text": "%s %s %s", "tooltip": "%s devices connected", "class": "connected"}\n' "$ICON" "$count" "$SEP" "$count"
    else
        printf '{"text": "%s %s %s", "tooltip": "Connected: %s", "class": "connected"}\n' "$ICON" "$device_name" "$SEP" "$device_name"
    fi
else
    printf '{"text": "%s on %s", "tooltip": "Bluetooth on, no devices", "class": "on"}\n' "$ICON" "$SEP"
fi
""";
    }
}
