namespace ThemeEngine.Generators;

public class FirefoxContentGenerator : IGenerator
{
    public string Name => "Firefox Content";
    public string OutputPath => ".config/firefox-theme/userContent.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;

        return $$"""
/* Auto-generated by ThemeEngine — do not edit manually */
/* Theme: {{theme.Name}} */
/* Styles web page content (links, new tab page, etc.) */

/* ---- Hyperlink colors ---- */
@-moz-document url-prefix("http"), url-prefix("https"), url-prefix("file") {
    a:link {
        color: {{c.Accent1}} !important;
    }

    a:visited {
        color: {{c.Accent2}} !important;
    }

    a:hover {
        color: {{c.Border}} !important;
    }

    a:active {
        color: {{c.Text}} !important;
    }
}

/* ---- Firefox new tab / home page ---- */
@-moz-document url("about:home"), url("about:newtab"), url("about:privatebrowsing") {
    body {
        background-color: {{c.Bg0}} !important;
        color: {{c.Text}} !important;
    }

    .search-wrapper input {
        background-color: {{c.Bg1}} !important;
        color: {{c.Text}} !important;
        border: 1px solid {{c.Inactive}} !important;
    }

    .search-wrapper input:focus {
        border-color: {{c.Border}} !important;
    }
}

/* ---- about:blank ---- */
@-moz-document url("about:blank") {
    body {
        background-color: {{c.Bg0}} !important;
    }
}
""";
    }
}
