namespace ThemeEngine.Generators;

public class FirefoxPrefsGenerator : IGenerator
{
    public string Name => "Firefox Prefs";
    public string OutputPath => ".config/firefox-theme/user-prefs.js";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var isLight = theme.Gtk.ColorScheme.Contains("light");
        // 0 = dark, 1 = light, 2 = system, 3 = browser
        var colorSchemeOverride = isLight ? "1" : "0";

        return $$"""
// Auto-generated by ThemeEngine — do not edit manually
// Theme: {{theme.Name}}
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("layout.css.prefers-color-scheme.content-override", {{colorSchemeOverride}});
""";
    }
}
