namespace ThemeEngine.Generators;

public class FirefoxGenerator : IGenerator
{
    public string Name => "Firefox";
    public string OutputPath => ".config/firefox-theme/userChrome.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;

        return $$"""
/* Auto-generated by ThemeEngine — do not edit manually */
/* Theme: {{theme.Name}} */
/* Enable in about:config: toolkit.legacyUserProfileCustomizations.stylesheets = true */

/* ---- Root variables ---- */
:root {
    --er-bg0: {{c.Bg0}};
    --er-bg1: {{c.Bg1}};
    --er-bg2: {{c.Bg2}};
    --er-bg3: {{c.Bg3}};
    --er-border: {{c.Border}};
    --er-accent1: {{c.Accent1}};
    --er-accent2: {{c.Accent2}};
    --er-text: {{c.Text}};
    --er-text-dim: {{c.TextDim}};
    --er-inactive: {{c.Inactive}};
    --er-red: {{c.Red}};

    /* Override Firefox built-in accent/focus colors */
    --focus-outline-color: var(--er-border) !important;
    --toolbar-bgcolor: var(--er-bg0) !important;
    --toolbar-color: var(--er-text) !important;
    --toolbar-field-background-color: var(--er-bg1) !important;
    --toolbar-field-color: var(--er-text) !important;
    --toolbar-field-border-color: var(--er-inactive) !important;
    --toolbar-field-focus-border-color: var(--er-border) !important;
    --lwt-accent-color: var(--er-bg0) !important;
    --lwt-text-color: var(--er-text) !important;
    --lwt-toolbar-field-highlight: var(--er-border) !important;
    --arrowpanel-background: var(--er-bg1) !important;
    --arrowpanel-color: var(--er-text) !important;
    --arrowpanel-border-color: var(--er-bg2) !important;
    --panel-separator-color: var(--er-bg2) !important;
    --tab-selected-bgcolor: var(--er-bg1) !important;
    --tab-selected-textcolor: var(--er-text) !important;
    --autocomplete-popup-highlight-background: var(--er-bg2) !important;
    --autocomplete-popup-highlight-color: var(--er-accent1) !important;
    --urlbar-box-bgcolor: var(--er-bg1) !important;
    --urlbar-box-hover-bgcolor: var(--er-bg2) !important;
    --urlbar-box-active-bgcolor: var(--er-bg2) !important;
    --urlbar-box-focus-bgcolor: var(--er-bg1) !important;
    --sidebar-background-color: var(--er-bg0) !important;
    --sidebar-text-color: var(--er-text) !important;
    --sidebar-border-color: var(--er-bg2) !important;
    color-scheme: dark !important;
}

/* ---- Tab bar ---- */
#TabsToolbar {
    background-color: var(--er-bg0) !important;
}

.tabbrowser-tab .tab-background {
    background-color: var(--er-bg0) !important;
    border: none !important;
}

.tabbrowser-tab[selected] .tab-background {
    background-color: var(--er-bg1) !important;
    border-bottom: 2px solid var(--er-border) !important;
}

.tabbrowser-tab .tab-label {
    color: var(--er-text-dim) !important;
}

.tabbrowser-tab[selected] .tab-label {
    color: var(--er-text) !important;
}

.tabbrowser-tab:hover:not([selected]) .tab-background {
    background-color: var(--er-bg1) !important;
}

/* ---- Navigation bar (URL bar area) ---- */
#nav-bar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

/* URL bar */
#urlbar-background {
    background-color: var(--er-bg1) !important;
    border: 1px solid var(--er-inactive) !important;
    border-radius: 4px !important;
}

#urlbar:hover #urlbar-background {
    border-color: var(--er-border) !important;
}

#urlbar[focused] #urlbar-background {
    border-color: var(--er-border) !important;
}

#urlbar-input {
    color: var(--er-text) !important;
}

/* ---- Toolbar buttons ---- */
#nav-bar toolbarbutton,
#TabsToolbar toolbarbutton {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#nav-bar toolbarbutton image,
#TabsToolbar toolbarbutton image {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#nav-bar toolbarbutton:hover,
#TabsToolbar toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
    border-radius: 4px !important;
}

#nav-bar toolbarbutton:hover image,
#TabsToolbar toolbarbutton:hover image {
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
}

#nav-bar toolbarbutton:active,
#TabsToolbar toolbarbutton:active {
    background-color: var(--er-bg2) !important;
}

/* ---- Bookmarks bar ---- */
#PersonalToolbar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

#PlacesToolbarItems toolbarbutton {
    color: var(--er-text-dim) !important;
}

#PlacesToolbarItems toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    color: var(--er-accent1) !important;
}

/* ---- Sidebar ---- */
#sidebar-header {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

#sidebar-box {
    background-color: var(--er-bg0) !important;
}

/* ---- Sidebar splitter / resize border ---- */
#sidebar-splitter {
    border-color: var(--er-bg2) !important;
    background-color: var(--er-bg2) !important;
}

#sidebar-splitter:hover {
    border-color: var(--er-border) !important;
    background-color: var(--er-border) !important;
}

/* ---- Global focus/selection overrides ---- */
*:focus-visible {
    outline-color: var(--er-border) !important;
}

::selection {
    background-color: var(--er-border) !important;
    color: var(--er-bg0) !important;
}

/* ---- Findbar ---- */
findbar {
    background-color: var(--er-bg1) !important;
    border-top: 1px solid var(--er-bg2) !important;
    color: var(--er-text) !important;
}

/* ---- Autocomplete / dropdown popups ---- */
.autocomplete-richlistbox {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
}

.autocomplete-richlistitem:hover {
    background-color: var(--er-bg2) !important;
}

/* ---- New tab button ---- */
#tabs-newtab-button:hover {
    background-color: var(--er-bg1) !important;
}

/* ---- Close tab button ---- */
.tab-close-button:hover {
    background-color: var(--er-red) !important;
    border-radius: 50%;
}
""";
    }
}
