namespace ThemeEngine.Generators;

public class FirefoxGenerator : IGenerator
{
    public string Name => "Firefox";
    public string OutputPath => ".config/firefox-theme/userChrome.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        return $$"""
/* Auto-generated by ThemeEngine — do not edit manually */
/* Theme: {{theme.Name}} */
/* Colors are driven by the Theme API (browser.theme.update) at runtime. */
/* This CSS references --lwt-* variables so it auto-updates when the theme changes. */

/* ---- Root variables ---- */
/* Map --er-* aliases to Firefox lightweight theme variables set by browser.theme.update(). */
/* Fallbacks use the current theme's colors for when no theme extension is active. */
:root {
    --er-bg0: var(--lwt-accent-color, {{theme.Colors.Bg0}});
    --er-bg1: var(--lwt-toolbar-field-background-color, {{theme.Colors.Bg1}});
    --er-bg2: var(--arrowpanel-border-color, {{theme.Colors.Bg2}});
    --er-bg3: {{theme.Colors.Bg3}};
    --er-border: var(--lwt-toolbar-field-focus-border-color, {{theme.Colors.Border}});
    --er-accent1: {{theme.Colors.Accent1}};
    --er-accent2: {{theme.Colors.Accent2}};
    --er-text: var(--lwt-text-color, {{theme.Colors.Text}});
    --er-text-dim: {{theme.Colors.TextDim}};
    --er-inactive: var(--lwt-toolbar-field-border-color, {{theme.Colors.Inactive}});
    --er-red: {{theme.Colors.Red}};
}

/* ---- Tab bar ---- */
#TabsToolbar {
    background-color: var(--er-bg0) !important;
}

.tabbrowser-tab .tab-background {
    background-color: var(--er-bg0) !important;
    border: none !important;
}

.tabbrowser-tab[selected] .tab-background {
    background-color: var(--er-bg1) !important;
    border-bottom: 2px solid var(--er-border) !important;
}

.tabbrowser-tab .tab-label {
    color: var(--er-text-dim) !important;
}

.tabbrowser-tab[selected] .tab-label {
    color: var(--er-text) !important;
}

.tabbrowser-tab:hover:not([selected]) .tab-background {
    background-color: var(--er-bg1) !important;
}

/* ---- Navigation bar (URL bar area) ---- */
#nav-bar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

/* URL bar */
#urlbar-background {
    background-color: var(--er-bg1) !important;
    border: 1px solid var(--er-inactive) !important;
    border-radius: 4px !important;
}

#urlbar:hover #urlbar-background {
    border-color: var(--er-border) !important;
}

#urlbar[focused] #urlbar-background {
    border-color: var(--er-border) !important;
}

#urlbar-input {
    color: var(--er-text) !important;
}

/* ---- Toolbar buttons ---- */
#nav-bar toolbarbutton,
#TabsToolbar toolbarbutton {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#nav-bar toolbarbutton image,
#TabsToolbar toolbarbutton image {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#nav-bar toolbarbutton:hover,
#TabsToolbar toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
    border-radius: 4px !important;
}

#nav-bar toolbarbutton:hover image,
#TabsToolbar toolbarbutton:hover image {
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
}

#nav-bar toolbarbutton:active,
#TabsToolbar toolbarbutton:active {
    background-color: var(--er-bg2) !important;
}

/* ---- Bookmarks bar ---- */
#PersonalToolbar {
    background-color: var(--er-bg0) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

#PlacesToolbarItems toolbarbutton {
    color: var(--er-text-dim) !important;
}

#PlacesToolbarItems toolbarbutton:hover {
    background-color: var(--er-bg1) !important;
    color: var(--er-accent1) !important;
}

/* ---- Sidebar ---- */
#sidebar-header {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
    border-bottom: 1px solid var(--er-bg2) !important;
}

#sidebar-box {
    background-color: var(--er-bg0) !important;
}

/* ---- Vertical sidebar (Firefox 131+) ---- */
#sidebar-main {
    background-color: var(--er-bg0) !important;
    color: var(--er-text) !important;
}

#sidebar-launcher {
    background-color: var(--er-bg0) !important;
}

#sidebar-launcher toolbarbutton,
#sidebar-launcher .sidebar-launcher-button {
    fill: var(--er-text-dim) !important;
    color: var(--er-text-dim) !important;
}

#sidebar-launcher toolbarbutton:hover,
#sidebar-launcher .sidebar-launcher-button:hover {
    background-color: var(--er-bg1) !important;
    fill: var(--er-accent1) !important;
    color: var(--er-accent1) !important;
}

#sidebar-launcher toolbarbutton[checked],
#sidebar-launcher .sidebar-launcher-button[active] {
    background-color: var(--er-bg1) !important;
    fill: var(--er-border) !important;
    color: var(--er-border) !important;
}

/* ---- Sidebar splitter / resize border ---- */
#sidebar-splitter {
    border-color: var(--er-bg2) !important;
    background-color: var(--er-bg2) !important;
}

#sidebar-splitter:hover {
    border-color: var(--er-border) !important;
    background-color: var(--er-border) !important;
}

/* ---- Global focus/selection overrides ---- */
*:focus-visible {
    outline-color: var(--er-border) !important;
}

::selection {
    background-color: var(--er-border) !important;
    color: var(--er-bg0) !important;
}

/* ---- Findbar ---- */
findbar {
    background-color: var(--er-bg1) !important;
    border-top: 1px solid var(--er-bg2) !important;
    color: var(--er-text) !important;
}

/* ---- Autocomplete / dropdown popups ---- */
.autocomplete-richlistbox {
    background-color: var(--er-bg1) !important;
    color: var(--er-text) !important;
}

.autocomplete-richlistitem:hover {
    background-color: var(--er-bg2) !important;
}

/* ---- New tab button ---- */
#tabs-newtab-button:hover {
    background-color: var(--er-bg1) !important;
}

/* ---- Close tab button ---- */
.tab-close-button:hover {
    background-color: var(--er-red) !important;
    border-radius: 50%;
}
""";
    }
}
