namespace ThemeEngine.Generators;

public class GtkCssGenerator : IGenerator
{
    public string Name => "GTK CSS";
    public string OutputPath => ".config/gtk-3.0/gtk.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;

        return $$"""
/* Auto-generated by ThemeEngine — do not edit manually */
/* Theme: {{theme.Name}} */

window, dialog {
    background-color: {{c.Bg0}};
    color: {{c.Text}};
}

headerbar, .titlebar {
    background-color: {{c.Bg1}};
    color: {{c.Text}};
    border-bottom: 1px solid {{c.Bg2}};
}

headerbar:backdrop, .titlebar:backdrop {
    background-color: {{c.Bg0}};
    color: {{c.Inactive}};
}

button {
    background-color: {{c.Bg2}};
    color: {{c.Text}};
    border: 1px solid {{c.Inactive}};
    border-radius: 4px;
}

button:hover {
    background-color: {{c.Bg3}};
    border-color: {{c.Border}};
}

button:active, button:checked {
    background-color: {{c.Border}};
    color: {{c.Bg0}};
}

scale trough {
    background-color: {{c.Bg2}};
    border-radius: 4px;
}

scale highlight {
    background-color: {{c.Border}};
    border-radius: 4px;
}

scale slider {
    background-color: {{c.Accent1}};
    border: 1px solid {{c.Accent2}};
    border-radius: 50%;
}

row, list row {
    background-color: {{c.Bg0}};
    color: {{c.Text}};
}

row:hover, list row:hover {
    background-color: {{c.Bg1}};
}

row:selected, list row:selected {
    background-color: {{c.Bg2}};
    color: {{c.Accent1}};
}

notebook tab {
    background-color: {{c.Bg0}};
    color: {{c.TextDim}};
    border: 1px solid {{c.Bg2}};
}

notebook tab:checked {
    background-color: {{c.Bg1}};
    color: {{c.Accent1}};
    border-bottom-color: {{c.Border}};
}

entry {
    background-color: {{c.Bg1}};
    color: {{c.Text}};
    border: 1px solid {{c.Inactive}};
    border-radius: 4px;
}

entry:focus {
    border-color: {{c.Border}};
}

combobox button {
    background-color: {{c.Bg1}};
    color: {{c.Text}};
}

scrollbar slider {
    background-color: {{c.Inactive}};
    border-radius: 4px;
}

scrollbar slider:hover {
    background-color: {{c.Border}};
}

menu, popover {
    background-color: {{c.Bg1}};
    color: {{c.Text}};
    border: 1px solid {{c.Bg2}};
}

menu menuitem:hover {
    background-color: {{c.Bg2}};
    color: {{c.Accent1}};
}

tooltip, tooltip.background {
    background-color: {{c.Bg1}};
    color: {{c.Text}};
    border: 1px solid {{c.Border}};
    border-radius: 4px;
}

/* Treeview (blueman, file pickers, etc.) */
treeview, treeview.view {
    background-color: {{c.Bg0}};
    color: {{c.Text}};
}

treeview:selected, treeview.view:selected,
treeview row:selected, treeview.view row:selected {
    background-color: {{c.Bg2}};
    color: {{c.Accent1}};
}

treeview:hover, treeview.view:hover {
    background-color: {{c.Bg1}};
}

treeview header button {
    background-color: {{c.Bg1}};
    color: {{c.TextDim}};
    border-bottom: 1px solid {{c.Bg2}};
}

/* Global selection override */
*:selected {
    background-color: {{c.Bg2}};
    color: {{c.Accent1}};
}

*:selected:focus {
    background-color: {{ColorHelper.ToCssRgba(c.Border, 0.12)}};
    color: {{c.Accent1}};
}

/* Toolbar / action bar */
toolbar, .toolbar, actionbar {
    background-color: {{c.Bg1}};
    border-bottom: 1px solid {{c.Bg2}};
}

/* Statusbar */
statusbar {
    background-color: {{c.Bg0}};
    color: {{c.TextDim}};
}

/* Switch toggle (bluetooth toggle) */
switch {
    background-color: {{c.Bg2}};
    border: 1px solid {{c.Inactive}};
    border-radius: 14px;
}

switch:checked {
    background-color: {{c.Border}};
}

switch slider {
    background-color: {{c.Text}};
    border-radius: 50%;
}
""";
    }
}
