namespace ThemeEngine.Generators;

public class GtkSettingsGenerator : IGenerator
{
    public string Name => "GTK Settings";
    public string OutputPath => ".config/gtk-3.0/settings.ini";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var gtk = theme.Gtk;
        var f = theme.Font;

        return $$"""
# Auto-generated by ThemeEngine
# Theme: {{theme.Name}}
[Settings]
gtk-application-prefer-dark-theme=1
gtk-theme-name={{gtk.Theme}}
gtk-font-name={{f.Family}} 11
gtk-cursor-theme-size=24
gtk-toolbar-style=GTK_TOOLBAR_BOTH_HORIZ
gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR
gtk-button-images=0
gtk-menu-images=0
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
""";
    }
}
