namespace ThemeEngine.Generators;

public class HyprpaperGenerator : IGenerator
{
    public string Name => "Hyprpaper";
    public string OutputPath => ".config/hypr/hyprpaper.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var images = theme.Wallpapers.Images;

        // No static images means this theme runs entirely on mpvpaper
        // (videos/Lotties). Emit a minimal hyprpaper config that doesn't
        // pre-load anything — mpvpaper takes over from the wallpaper-cycler.
        if (images.Length == 0)
        {
            return $"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {theme.Name}
# (No static images; wallpaper handled by mpvpaper.)

splash = false
ipc = true
""";
        }

        var pick = images[Random.Shared.Next(images.Length)];
        var path = $"~/.config/hypr/wallpapers/{pick}";

        var preloads = string.Join("\n", images.Select(i => $"preload = ~/.config/hypr/wallpapers/{i}"));

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

{{preloads}}

wallpaper {
    monitor =
    path = {{path}}
}

splash = false
ipc = true
""";
    }
}
