namespace ThemeEngine.Generators;

public class HyprpaperGenerator : IGenerator
{
    public string Name => "Hyprpaper";
    public string OutputPath => ".config/hypr/hyprpaper.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var images = theme.Wallpapers.Images;
        var pick = images[Random.Shared.Next(images.Length)];
        var path = $"~/.config/hypr/wallpapers/{pick}";

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

wallpaper {
    monitor =
    path = {{path}}
    fit_mode = {{theme.Wallpapers.FitMode}}
}

splash = false
ipc = true
""";
    }
}
