namespace ThemeEngine.Generators;

public class HyprchatGenerator : IGenerator
{
  public string Name => "HyprChat";
  public string OutputPath => ".config/hyprchat/theme.jsonc";

  public string Generate(Theme theme, string wallpapersDir)
  {
    var c = theme.Colors;
    var f = theme.Font;
    var dangerBg = ColorHelper.MixColors(c.Red, c.Bg0, 0.25);

    return $$"""
        // Auto-generated by ThemeEngine — do not edit manually
        // Theme: {{theme.Name}}
        {
          "bg0": "{{c.Bg0}}",
          "bg1": "{{c.Bg1}}",
          "bg2": "{{c.Bg2}}",
          "bg3": "{{c.Bg3}}",
          "border": "{{c.Border}}",
          "accent1": "{{c.Accent1}}",
          "accent2": "{{c.Accent2}}",
          "text": "{{c.Text}}",
          "textDim": "{{c.TextDim}}",
          "danger": "{{c.Red}}",
          "dangerBg": "{{dangerBg}}",
          "fontFamily": "{{f.Family}}",
          "fontSize": {{f.Size + 2}}
        }
        """;
  }
}
