using System.Globalization;

namespace ThemeEngine.Generators;

public class HyprtoolkitGenerator : IGenerator
{
    public string Name => "Hyprtoolkit";
    public string OutputPath => ".config/hypr/hyprtoolkit.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;
        var h = theme.Hyprland;

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

background = 0xFF{{StripHash(c.Bg0)}}
base = 0xFF{{StripHash(c.Bg1)}}
text = 0xFF{{StripHash(c.Text)}}
alternate_base = 0xFF{{StripHash(c.Bg2)}}
bright_text = 0xFF{{StripHash(c.Accent1)}}
accent = 0xFF{{StripHash(c.Border)}}
accent_secondary = 0xFF{{StripHash(c.Accent2)}}

font_family = {{f.Family}}
font_family_monospace = {{f.Family}}
font_size = 13
h1_size = 19
h2_size = 15
h3_size = 13
small_font_size = 10

rounding_large = {{h.Rounding + 4}}
rounding_small = {{h.Rounding}}
""";
    }

    private static string StripHash(string hex) => hex.TrimStart('#');
}
