using System.Globalization;

namespace ThemeEngine.Generators;

public class HyprlandGenerator : IGenerator
{
    public string Name => "Hyprland";
    public string OutputPath => ".config/hypr/theme.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var h = theme.Hyprland;
        var inv = CultureInfo.InvariantCulture;

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

general {
    gaps_in = {{h.GapsIn}}
    gaps_out = {{h.GapsOut}}
    border_size = {{h.BorderSize}}
    col.active_border = rgba({{ColorHelper.ToHyprRgba(c.Border)}}) rgba({{ColorHelper.ToHyprRgba(c.Accent2)}}) 45deg
    col.inactive_border = rgba({{ColorHelper.ToHyprRgba(c.Inactive, "aa")}})
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = {{h.Rounding}}
    rounding_power = 2
    active_opacity = {{h.ActiveOpacity.ToString(inv)}}
    inactive_opacity = {{h.InactiveOpacity.ToString(inv)}}

    shadow {
        enabled = true
        range = {{h.ShadowRange}}
        render_power = {{h.ShadowRenderPower}}
        color = rgba({{ColorHelper.ToHyprRgba(c.Bg1)}})
    }

    blur {
        enabled = true
        size = {{h.BlurSize}}
        passes = {{h.BlurPasses}}
        vibrancy = {{h.BlurVibrancy.ToString(inv)}}
    }
}

animations {
    enabled = yes, please :)

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = global,        1,     {{h.AnimationSpeedGlobal.ToString(inv)}},    default
    animation = border,        1,     {{h.AnimationSpeedBorder.ToString(inv)}},     easeOutQuint
    animation = windows,       1,     {{h.AnimationSpeedWindows.ToString(inv)}},   easeOutQuint
    animation = windowsIn,     1,     {{h.AnimationSpeedWindowsIn.ToString(inv)}},     easeOutQuint, popin 87%
    animation = windowsOut,    1,     {{h.AnimationSpeedWindowsOut.ToString(inv)}},     linear,       popin 87%
    animation = fadeIn,        1,     {{h.AnimationSpeedFadeIn.ToString(inv)}},   almostLinear
    animation = fadeOut,       1,     {{h.AnimationSpeedFadeOut.ToString(inv)}},     almostLinear
    animation = fade,          1,     3.5,   quick
    animation = layers,        1,     4.5,   easeOutQuint
    animation = layersIn,      1,     4.5,   easeOutQuint, fade
    animation = layersOut,     1,     2,     linear,       fade
    animation = fadeLayersIn,  1,     2.5,   almostLinear
    animation = fadeLayersOut, 1,     1.8,   almostLinear
    animation = workspaces,    1,     {{h.AnimationSpeedWorkspaces.ToString(inv)}},     almostLinear, fade
    animation = workspacesIn,  1,     2,     almostLinear, fade
    animation = workspacesOut, 1,     {{h.AnimationSpeedWorkspaces.ToString(inv)}},     almostLinear, fade
    animation = zoomFactor,    1,     8,     quick
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 0
}

# GTK theme for GTK4 apps (Nautilus, etc.)
env = GTK_THEME,{{theme.Gtk.Theme}}
""";
    }
}
