namespace ThemeEngine.Generators;

public class HyprlockGenerator : IGenerator
{
    public string Name => "Hyprlock";
    public string OutputPath => ".config/hypr/hyprlock.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;

        // Pick a random wallpaper for the lock screen
        var images = theme.Wallpapers.Images;
        var pick = images[Random.Shared.Next(images.Length)];
        var bgPath = $"~/.config/hypr/wallpapers/{pick}";
        var isLight = theme.Gtk.ColorScheme.Contains("light");
        var brightness = isLight ? "1.2" : "0.6";

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

background {
    path = {{bgPath}}
    blur_passes = 3
    blur_size = 6
    brightness = {{brightness}}
}

input-field {
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb({{StripHash(c.Border)}})
    inner_color = rgb({{StripHash(c.Bg1)}})
    font_color = rgb({{StripHash(c.Text)}})
    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
    hide_input = false
    check_color = rgb({{StripHash(c.Green)}})
    fail_color = rgb({{StripHash(c.Red)}})
    fail_text = <i>$FAIL</i>
    capslock_color = rgb({{StripHash(c.Accent2)}})
    position = 0, -80
    halign = center
    valign = center
    font_family = {{f.Family}}
}

label {
    text = $TIME
    color = rgb({{StripHash(c.Text)}})
    font_size = 64
    font_family = {{f.Family}}
    shadow_passes = 2
    shadow_size = 4
    shadow_color = rgb({{StripHash(c.Bg0)}})
    position = 0, 80
    halign = center
    valign = center
}

label {
    text = $USER
    color = rgb({{StripHash(c.Text)}})
    font_size = 16
    font_family = {{f.Family}}
    shadow_passes = 2
    shadow_size = 3
    shadow_color = rgb({{StripHash(c.Bg0)}})
    position = 0, -20
    halign = center
    valign = center
}
""";
    }

    private static string StripHash(string hex) => hex.TrimStart('#');
}
