namespace ThemeEngine.Generators;

public class KittyGenerator : IGenerator
{
    public string Name => "Kitty";
    public string OutputPath => ".config/kitty/kitty.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;
        var isLight = theme.Gtk.ColorScheme.Contains("light");

        var sat = c.SaturationBoost;

        // Derive a proper cyan distinct from blue
        var cyan = ColorHelper.MixColors(c.Blue, c.Green, 0.40);

        // Boost saturation, then adjust lightness for contrast against the background:
        // Light mode — darken so colors stand out on white
        // Dark mode — lighten so colors don't look muddy on black
        var ansiRed = ColorHelper.AdjustSaturation(c.Red, sat);
        var ansiGreen = ColorHelper.AdjustSaturation(c.Green, sat);
        var ansiYellow = ColorHelper.AdjustSaturation(c.Border, sat);
        var ansiBlue = ColorHelper.AdjustSaturation(c.Blue, sat);
        var ansiMagenta = ColorHelper.AdjustSaturation(c.Accent2, sat);
        var ansiCyan = ColorHelper.AdjustSaturation(cyan, sat);

        if (isLight)
        {
            const double d = 0.20;
            ansiRed = ColorHelper.Darken(ansiRed, d);
            ansiGreen = ColorHelper.Darken(ansiGreen, d);
            ansiYellow = ColorHelper.Darken(ansiYellow, d);
            ansiBlue = ColorHelper.Darken(ansiBlue, d);
            ansiMagenta = ColorHelper.Darken(ansiMagenta, d);
            ansiCyan = ColorHelper.Darken(ansiCyan, d);
        }
        else
        {
            const double l = 0.10;
            ansiRed = ColorHelper.Lighten(ansiRed, l);
            ansiGreen = ColorHelper.Lighten(ansiGreen, l);
            ansiYellow = ColorHelper.Lighten(ansiYellow, l);
            ansiBlue = ColorHelper.Lighten(ansiBlue, l);
            ansiMagenta = ColorHelper.Lighten(ansiMagenta, l);
            ansiCyan = ColorHelper.Lighten(ansiCyan, l);
        }

        // Bright variants: visibly shifted from their normal counterparts
        var brightBlack = isLight ? ColorHelper.Darken(c.Inactive, 0.10) : ColorHelper.Lighten(c.Inactive, 0.10);
        var brightRed = isLight ? ColorHelper.Darken(ansiRed, 0.12) : ColorHelper.Lighten(ansiRed, 0.12);
        var brightGreen = isLight ? ColorHelper.Darken(ansiGreen, 0.12) : ColorHelper.Lighten(ansiGreen, 0.12);
        var brightYellow = isLight ? ColorHelper.Darken(c.Accent1, 0.08) : ColorHelper.Lighten(c.Accent1, 0.08);
        var brightBlue = isLight ? ColorHelper.Darken(ansiBlue, 0.12) : ColorHelper.Lighten(ansiBlue, 0.12);
        var brightMagenta = isLight ? ColorHelper.Darken(ansiMagenta, 0.12) : ColorHelper.Lighten(ansiMagenta, 0.12);
        var brightCyan = isLight ? ColorHelper.Darken(ansiCyan, 0.12) : ColorHelper.Lighten(ansiCyan, 0.12);
        var brightWhite = isLight ? ColorHelper.Darken(c.TextDim, 0.08) : ColorHelper.Lighten(c.TextDim, 0.08);

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

# Font
font_family {{f.Family}}
font_size {{f.Size - 2}}

# Colors
foreground {{c.Text}}
background {{c.Bg0}}
selection_foreground {{c.Bg0}}
selection_background {{c.Border}}
cursor {{c.Border}}
cursor_text_color {{c.Bg0}}
url_color {{c.Accent1}}

# Window
background_opacity 0.92
window_padding_width 8
window_margin_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Remote control (needed for live theme reload)
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# Tab bar
active_tab_foreground {{c.Accent1}}
active_tab_background {{c.Bg1}}
active_tab_font_style bold
inactive_tab_foreground {{c.TextDim}}
inactive_tab_background {{c.Bg0}}
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Terminal bell
enable_audio_bell no
visual_bell_duration 0

# ANSI colors
# black (used as dark foreground/background by TUIs)
color0 {{c.Bg3}}
color8 {{brightBlack}}

# red
color1 {{ansiRed}}
color9 {{brightRed}}

# green
color2 {{ansiGreen}}
color10 {{brightGreen}}

# yellow
color3 {{ansiYellow}}
color11 {{brightYellow}}

# blue
color4 {{ansiBlue}}
color12 {{brightBlue}}

# magenta
color5 {{ansiMagenta}}
color13 {{brightMagenta}}

# cyan
color6 {{ansiCyan}}
color14 {{brightCyan}}

# white (used as light foreground/background by TUIs)
color7 {{c.Text}}
color15 {{brightWhite}}
""";
    }
}
