using System.Globalization;

namespace ThemeEngine.Generators;

public class KittyGenerator : IGenerator
{
    public string Name => "Kitty";
    public string OutputPath => ".config/kitty/kitty.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var f = theme.Font;
        var p = PaletteResolver.Resolve(theme);
        var inv = CultureInfo.InvariantCulture;
        var opacity = (theme.Terminal?.EffectiveOpacity ?? 1.0).ToString(inv);

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

# Font
font_family {{f.Family}}
font_size {{f.Size - 2}}

# Colors
foreground {{p.Text}}
background {{p.Bg0}}

# Selection — high-contrast pair so highlighted text is always visible,
# even when the terminal window is translucent and a busy wallpaper is
# bleeding through.
selection_foreground {{p.SelectionFg}}
selection_background {{p.SelectionBg}}

cursor {{p.Border}}
cursor_text_color {{p.Bg0}}
url_color {{p.Accent1}}

# Window
background_opacity {{opacity}}
window_padding_width 8
window_margin_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Remote control (needed for live theme reload)
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# Tab bar
active_tab_foreground {{p.Accent1}}
active_tab_background {{p.Bg1}}
active_tab_font_style bold
inactive_tab_foreground {{p.TextDim}}
inactive_tab_background {{p.Bg0}}
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Terminal bell
enable_audio_bell no
visual_bell_duration 0

# ANSI colors — every slot is contrast-checked (WCAG AAA against the
# background) and perceptually distinct from its neighbors.
# black (used as dark foreground/background by TUIs)
color0 {{p.AnsiBlack}}
color8 {{p.BrightBlack}}

# red
color1 {{p.AnsiRed}}
color9 {{p.BrightRed}}

# green
color2 {{p.AnsiGreen}}
color10 {{p.BrightGreen}}

# yellow
color3 {{p.AnsiYellow}}
color11 {{p.BrightYellow}}

# blue
color4 {{p.AnsiBlue}}
color12 {{p.BrightBlue}}

# magenta
color5 {{p.AnsiMagenta}}
color13 {{p.BrightMagenta}}

# cyan
color6 {{p.AnsiCyan}}
color14 {{p.BrightCyan}}

# white (used as light foreground/background by TUIs)
color7 {{p.AnsiWhite}}
color15 {{p.BrightWhite}}
""";
    }
}
