namespace ThemeEngine.Generators;

public class KittyGenerator : IGenerator
{
    public string Name => "Kitty";
    public string OutputPath => ".config/kitty/kitty.conf";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;
        var isLight = theme.Gtk.ColorScheme.Contains("light");

        // ANSI colors must flip for light/dark mode
        // TUIs assume: black=dark, white=light
        // Dark theme: black shades dark, white shades light — normal
        // Light theme: black should still be dark, white should still be light
        //   but "bright" versions adjust for contrast on the light bg

        return $$"""
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}

# Font
font_family {{f.Family}}
font_size {{f.Size - 2}}

# Colors
foreground {{c.Text}}
background {{c.Bg0}}
selection_foreground {{c.Bg0}}
selection_background {{c.Border}}
cursor {{c.Border}}
cursor_text_color {{c.Bg0}}
url_color {{c.Accent1}}

# Window
background_opacity 0.92
window_padding_width 8
window_margin_width 0
hide_window_decorations yes
confirm_os_window_close 0

# Remote control (needed for live theme reload)
allow_remote_control yes
listen_on unix:/tmp/kitty-socket

# Tab bar
active_tab_foreground {{c.Accent1}}
active_tab_background {{c.Bg1}}
active_tab_font_style bold
inactive_tab_foreground {{c.TextDim}}
inactive_tab_background {{c.Bg0}}
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Terminal bell
enable_audio_bell no
visual_bell_duration 0

# ANSI colors
# black (used as dark foreground/background by TUIs)
color0 {{c.Bg3}}
color8 {{c.Inactive}}

# red
color1 {{c.Red}}
color9 {{c.Red}}

# green
color2 {{c.Green}}
color10 {{c.Green}}

# yellow
color3 {{c.Border}}
color11 {{c.Accent1}}

# blue
color4 {{c.Blue}}
color12 {{c.Blue}}

# magenta
color5 {{c.Accent2}}
color13 {{c.Accent2}}

# cyan
color6 {{c.Blue}}
color14 {{c.Blue}}

# white (used as light foreground/background by TUIs)
color7 {{c.Text}}
color15 {{c.TextDim}}
""";
    }
}
