namespace ThemeEngine.Generators;

public class MpvpaperToggleGenerator : IGenerator
{
    public string Name => "Mpvpaper Toggle";
    public string OutputPath => ".config/hypr/scripts/mpvpaper-toggle.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var videos = theme.Wallpapers.Videos;
        var images = theme.Wallpapers.Images;

        var videoEntries = string.Join("\n", videos.Select(v => $"  \"$WALLPAPER_DIR/{v}\""));
        var imageEntries = string.Join("\n", images.Select(i => $"  \"$WALLPAPER_DIR/{i}\""));

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# Toggle between static (hyprpaper) and animated (mpvpaper) wallpaper.

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"

VIDEOS=(
{{videoEntries}}
)

IMAGES=(
{{imageEntries}}
)

pick_random() {
    local arr=("$@")
    echo "${arr[$((RANDOM % ${#arr[@]}))]}"
}

if pgrep -x mpvpaper > /dev/null; then
    # mpvpaper running → switch to static
    killall mpvpaper
    sleep 0.3

    IMAGE=$(pick_random "${IMAGES[@]}")
    cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by ThemeEngine
wallpaper {
    monitor =
    path = $IMAGE
    fit_mode = {{theme.Wallpapers.FitMode}}
}

splash = false
ipc = true
HYPR
    hyprpaper &
elif pgrep -x hyprpaper > /dev/null; then
    # hyprpaper running → switch to animated
    if ! command -v mpvpaper &> /dev/null; then
        notify-send "mpvpaper not installed" "Install mpvpaper from AUR to use animated wallpapers" 2>/dev/null || true
        exit 0
    fi
    killall hyprpaper 2>/dev/null || true
    sleep 0.3
    VIDEO=$(pick_random "${VIDEOS[@]}")
    monitors=$(hyprctl monitors -j | jq -r '.[].name')
    for mon in $monitors; do
        mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$VIDEO" &
    done
else
    # Nothing running → start hyprpaper
    hyprpaper &
fi
""";
    }
}
