namespace ThemeEngine.Generators;

public class NvimColorschemeGenerator : IGenerator
{
    public string Name => "Neovim Colorscheme";
    public string OutputPath => ".config/nvim/lua/plugins/colorscheme.lua";

    public string Generate(Theme theme, string wallpapersDir)
    {
        // No Nvim section -> dynamic mode: build a catppuccin spec whose
        // palette is overridden from the rest of the theme's colors. Honors
        // the theme's contrast guarantees and saturation boost.
        if (theme.Nvim is null)
        {
            return GenerateDynamic(theme);
        }

        // Nvim section present -> static mode: install the requested plugin
        // (if any) and tell LazyVim to use the named colorscheme.
        return GenerateStatic(theme, theme.Nvim);
    }

    private static string GenerateStatic(Theme theme, NvimSettings nvim)
    {
        var pluginSpec = nvim.Plugin is null
            ? string.Empty
            : BuildPluginSpec(nvim);

        return $$"""
            -- Auto-generated by ThemeEngine — do not edit manually
            -- Theme: {{theme.Name}}
            return {
            {{pluginSpec}}  {
                "LazyVim/LazyVim",
                opts = { colorscheme = "{{nvim.Colorscheme}}" },
              },
            }
            """;
    }

    private static string BuildPluginSpec(NvimSettings nvim)
    {
        var nameField = nvim.Name is null
            ? string.Empty
            : $"\n    name = \"{nvim.Name}\",";

        return $$"""
              {
                "{{nvim.Plugin}}",{{nameField}}
                lazy = false,
                priority = 1000,
              },

            """;
    }

    private static string GenerateDynamic(Theme theme)
    {
        var c = theme.Colors;
        var p = PaletteResolver.Resolve(theme);

        var sat = c.SaturationBoost;
        var minContrast = p.MinContrast;

        // --- Derive distinct syntax colors from the 13-color palette ---
        var syntaxKeyword = ColorHelper.AdjustSaturation(ColorHelper.ShiftHue(c.Blue, 90), sat + 0.05);
        var syntaxType = ColorHelper.AdjustSaturation(ColorHelper.MixColors(c.Blue, c.Green, 0.60), sat + 0.03);
        var syntaxMethod = ColorHelper.AdjustSaturation(ColorHelper.ShiftHue(c.Blue, -150), sat + 0.08);
        var syntaxCyan = ColorHelper.AdjustSaturation(ColorHelper.ShiftHue(c.Blue, -30), sat + 0.03);
        var syntaxSapphire = ColorHelper.AdjustSaturation(ColorHelper.ShiftHue(c.Blue, 40), sat + 0.02);
        var syntaxProperty = ColorHelper.AdjustSaturation(ColorHelper.MixColors(c.Accent1, c.Blue, 0.35), sat);
        var syntaxFlamingo = ColorHelper.AdjustSaturation(ColorHelper.MixColors(c.Red, c.Accent1, 0.40), sat + 0.03);
        var syntaxPink = ColorHelper.AdjustSaturation(ColorHelper.ShiftHue(c.Blue, 120), sat + 0.04);
        var syntaxRosewater = ColorHelper.MixColors(c.Text, c.Accent1, 0.15);
        var syntaxParam = ColorHelper.MixColors(c.Red, c.Text, 0.40);

        syntaxKeyword = ColorHelper.EnsureContrast(syntaxKeyword, c.Bg0, minContrast);
        syntaxType = ColorHelper.EnsureContrast(syntaxType, c.Bg0, minContrast);
        syntaxMethod = ColorHelper.EnsureContrast(syntaxMethod, c.Bg0, minContrast);
        syntaxCyan = ColorHelper.EnsureContrast(syntaxCyan, c.Bg0, minContrast);
        syntaxSapphire = ColorHelper.EnsureContrast(syntaxSapphire, c.Bg0, minContrast);
        syntaxProperty = ColorHelper.EnsureContrast(syntaxProperty, c.Bg0, minContrast);
        syntaxFlamingo = ColorHelper.EnsureContrast(syntaxFlamingo, c.Bg0, minContrast);
        syntaxPink = ColorHelper.EnsureContrast(syntaxPink, c.Bg0, minContrast);
        syntaxRosewater = ColorHelper.EnsureContrast(syntaxRosewater, c.Bg0, minContrast);
        syntaxParam = ColorHelper.EnsureContrast(syntaxParam, c.Bg0, minContrast);

        var distinctColors = ColorHelper.EnsureDistinct(
            [syntaxKeyword, syntaxType, syntaxMethod, syntaxCyan, syntaxSapphire,
             syntaxProperty, syntaxFlamingo, syntaxPink, syntaxRosewater, syntaxParam],
            c.Bg0);
        syntaxKeyword = distinctColors[0];
        syntaxType = distinctColors[1];
        syntaxMethod = distinctColors[2];
        syntaxCyan = distinctColors[3];
        syntaxSapphire = distinctColors[4];
        syntaxProperty = distinctColors[5];
        syntaxFlamingo = distinctColors[6];
        syntaxPink = distinctColors[7];
        syntaxRosewater = distinctColors[8];
        syntaxParam = distinctColors[9];

        syntaxKeyword = ColorHelper.EnsureContrast(syntaxKeyword, c.Bg0, minContrast);
        syntaxType = ColorHelper.EnsureContrast(syntaxType, c.Bg0, minContrast);
        syntaxMethod = ColorHelper.EnsureContrast(syntaxMethod, c.Bg0, minContrast);
        syntaxCyan = ColorHelper.EnsureContrast(syntaxCyan, c.Bg0, minContrast);
        syntaxSapphire = ColorHelper.EnsureContrast(syntaxSapphire, c.Bg0, minContrast);
        syntaxProperty = ColorHelper.EnsureContrast(syntaxProperty, c.Bg0, minContrast);
        syntaxFlamingo = ColorHelper.EnsureContrast(syntaxFlamingo, c.Bg0, minContrast);
        syntaxPink = ColorHelper.EnsureContrast(syntaxPink, c.Bg0, minContrast);
        syntaxRosewater = ColorHelper.EnsureContrast(syntaxRosewater, c.Bg0, minContrast);
        syntaxParam = ColorHelper.EnsureContrast(syntaxParam, c.Bg0, minContrast);

        var slotBlue = p.Blue;
        var slotGreen = p.Green;
        var slotRed = p.Red;
        var slotAccent2 = p.Accent2;

        var overlay1 = ColorHelper.MixColors(p.TextDim, p.Text, 0.2);
        var subtext1 = ColorHelper.MixColors(p.TextDim, p.Text, 0.4);

        return $$"""
            -- Auto-generated by ThemeEngine — do not edit manually
            -- Theme: {{theme.Name}}
            return {
              {
                "catppuccin/nvim",
                name = "catppuccin",
                lazy = false,
                priority = 1000,
                opts = {
                  flavour = "mocha",
                  integrations = { lsp = true, treesitter = true },
                  color_overrides = {
                    mocha = {
                      base = "{{c.Bg0}}",
                      mantle = "{{c.Bg1}}",
                      crust = "{{c.Bg0}}",
                      surface0 = "{{c.Bg2}}",
                      surface1 = "{{c.Bg3}}",
                      surface2 = "{{c.Inactive}}",
                      overlay0 = "{{p.TextDim}}",
                      overlay1 = "{{overlay1}}",
                      overlay2 = "{{p.Border}}",
                      text = "{{p.Text}}",
                      subtext0 = "{{p.TextDim}}",
                      subtext1 = "{{subtext1}}",

                      lavender = "{{syntaxProperty}}",
                      blue = "{{slotBlue}}",
                      sapphire = "{{syntaxSapphire}}",
                      sky = "{{syntaxCyan}}",
                      teal = "{{syntaxType}}",
                      green = "{{slotGreen}}",
                      yellow = "{{syntaxMethod}}",
                      peach = "{{slotAccent2}}",
                      maroon = "{{syntaxParam}}",
                      red = "{{slotRed}}",
                      mauve = "{{syntaxKeyword}}",
                      pink = "{{syntaxPink}}",
                      flamingo = "{{syntaxFlamingo}}",
                      rosewater = "{{syntaxRosewater}}",
                    },
                  },
                  custom_highlights = function(colors)
                    return {
                      ["@lsp.type.keyword.cs"] = { fg = colors.mauve },
                      ["@lsp.type.class.cs"] = { fg = colors.teal },
                      ["@lsp.type.struct.cs"] = { fg = colors.teal, bold = true },
                      ["@lsp.type.interface.cs"] = { fg = colors.sky, bold = true, italic = true },
                      ["@lsp.type.enum.cs"] = { fg = colors.sapphire },
                      ["@lsp.type.enumMember.cs"] = { fg = colors.flamingo },
                      ["@lsp.type.typeParameter.cs"] = { fg = colors.teal, italic = true },
                      ["@lsp.type.namespace.cs"] = { fg = colors.subtext0, italic = true },
                      ["@lsp.type.method.cs"] = { fg = colors.yellow },
                      ["@lsp.type.extensionMethodName.cs"] = { fg = colors.yellow, bold = true },
                      ["@lsp.type.property.cs"] = { fg = colors.lavender },
                      ["@lsp.type.field.cs"] = { fg = colors.lavender, italic = true },
                      ["@lsp.type.staticField.cs"] = { fg = colors.peach, bold = true },
                      ["@lsp.type.parameter.cs"] = { fg = colors.maroon, italic = true },
                      ["@lsp.type.variable.cs"] = { fg = colors.text },
                      ["@lsp.type.local.cs"] = { fg = colors.text },
                      ["@lsp.type.delegate.cs"] = { fg = colors.flamingo, italic = true },
                      ["@lsp.type.event.cs"] = { fg = colors.flamingo, bold = true },
                      ["@lsp.type.string.cs"] = { fg = colors.green },
                      ["@lsp.type.number.cs"] = { fg = colors.peach },
                      ["@lsp.type.operator.cs"] = { fg = colors.sky },

                      ["@keyword"] = { fg = colors.mauve },
                      ["@type"] = { fg = colors.teal },
                      ["@type.builtin"] = { fg = colors.teal, bold = true },
                      ["@function"] = { fg = colors.yellow },
                      ["@function.method"] = { fg = colors.yellow },
                      ["@function.builtin"] = { fg = colors.yellow, italic = true },
                      ["@constructor"] = { fg = colors.sapphire },
                      ["@string"] = { fg = colors.green },
                      ["@number"] = { fg = colors.peach },
                      ["@variable"] = { fg = colors.text },
                      ["@variable.parameter"] = { fg = colors.maroon, italic = true },
                      ["@property"] = { fg = colors.lavender },
                      ["@operator"] = { fg = colors.sky },
                      ["@punctuation"] = { fg = colors.rosewater },
                      ["@comment"] = { fg = colors.overlay0, italic = true },
                      ["@constant"] = { fg = colors.peach },
                      ["@constant.builtin"] = { fg = colors.peach, bold = true },
                      ["@tag"] = { fg = colors.flamingo },
                      ["@tag.attribute"] = { fg = colors.yellow },
                      ["@namespace"] = { fg = colors.subtext0, italic = true },
                    }
                  end,
                },
              },
              {
                "LazyVim/LazyVim",
                opts = { colorscheme = "catppuccin" },
              },
            }
            """;
    }
}
