namespace ThemeEngine.Generators;

public class NvimColorschemeGenerator : IGenerator
{
    public string Name => "Neovim Colorscheme";
    public string OutputPath => ".config/nvim/lua/plugins/colorscheme.lua";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;

        return $$"""
            -- Auto-generated by ThemeEngine — do not edit manually
            -- Theme: {{theme.Name}}
            return {
              {
                "catppuccin/nvim",
                name = "catppuccin",
                lazy = true,
                opts = {
                  flavour = "mocha",
                  integrations = { lsp = true, treesitter = true },
                  color_overrides = {
                    mocha = {
                      base = "{{c.Bg0}}",
                      mantle = "{{c.Bg1}}",
                      crust = "{{c.Bg0}}",
                      surface0 = "{{c.Bg2}}",
                      surface1 = "{{c.Bg3}}",
                      surface2 = "{{c.Inactive}}",
                      overlay0 = "{{c.TextDim}}",
                      overlay1 = "{{c.TextDim}}",
                      overlay2 = "{{c.Border}}",
                      text = "{{c.Text}}",
                      subtext0 = "{{c.TextDim}}",
                      subtext1 = "{{c.TextDim}}",
                      lavender = "{{c.Accent1}}",
                      blue = "{{c.Blue}}",
                      sapphire = "{{c.Blue}}",
                      sky = "{{c.Border}}",
                      teal = "{{c.Green}}",
                      green = "{{c.Green}}",
                      yellow = "{{c.Accent1}}",
                      peach = "{{c.Accent2}}",
                      maroon = "{{c.Red}}",
                      red = "{{c.Red}}",
                      mauve = "{{c.Border}}",
                      pink = "{{c.Accent2}}",
                      flamingo = "{{c.Accent1}}",
                      rosewater = "{{c.Text}}",
                    },
                  },
                  custom_highlights = function(colors)
                    return {
                      ["@lsp.type.interface.cs"] = {
                        fg = colors.sky,
                        style = { "bold", "italic" },
                      },
                      ["@lsp.type.class.cs"] = {
                        fg = colors.lavender,
                        style = {},
                      },
                      ["@lsp.type.extensionMethodName.cs"] = {
                        fg = colors.mauve,
                        style = { "bold" },
                      },
                      ["@lsp.type.variable.cs"] = {
                        fg = colors.text,
                        style = { "italic" },
                      },
                      ["@lsp.type.staticField.cs"] = {
                        fg = colors.peach,
                        style = { "bold" },
                      },
                    }
                  end,
                },
              },
              {
                "LazyVim/LazyVim",
                opts = { colorscheme = "catppuccin" },
              },
            }
            """;
    }
}
