using System.Text.Json;

namespace ThemeEngine.Generators;

public class QuickVisorThemeGenerator : IGenerator
{
    public string Name => "Quick Visor Theme";
    public string OutputPath => ".config/quick-visor/theme.jsonc";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var p = PaletteResolver.Resolve(theme);
        var f = theme.Font;

        var themeJson = new
        {
            fontFamily = f.Family,
            fontSize = Math.Max(12, f.Size + 2),
            background = c.Bg0,
            foreground = p.Text,
            idle = p.TextDim,
            accent = p.Accent1,
            warning = p.Red,
            overlayStrong = p.SelectionBg,
            overlayWeak = c.Bg2,
            border = p.Border,
            padding = Math.Max(6, theme.Hyprland.GapsIn),
            spacing = Math.Max(6, theme.Hyprland.GapsIn),
            radius = Math.Max(8, theme.Hyprland.Rounding * 2),
        };

        return $$"""
        // Auto-generated by ThemeEngine — do not edit manually
        // Theme: {{theme.Name}}
        {{JsonSerializer.Serialize(themeJson, new JsonSerializerOptions
        {
            WriteIndented = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        })}}
        """;
    }
}
