namespace ThemeEngine.Generators;

public class TemperatureScriptGenerator : IGenerator
{
    public string Name => "Temperature Script";
    public string OutputPath => ".config/hypr/scripts/temperature.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var sep = theme.Waybar.Separator;

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# CPU + GPU temperature for waybar

ICON=$'\uf2c9'
ICON_CRIT=$'\uf2c7'
SEP="<span color='{{c.Accent1}}'>{{sep}}</span>"
CRIT=80

get_cpu_temp() {
    # Try coretemp / k10temp first, then any hwmon with temp1_input
    for hwmon in /sys/class/hwmon/hwmon*; do
        name=$(cat "$hwmon/name" 2>/dev/null)
        case "$name" in
            coretemp|k10temp|zenpower)
                temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
                if [[ -n "$temp" ]]; then
                    echo $((temp / 1000))
                    return
                fi
                ;;
        esac
    done
    # Fallback: first hwmon with temp1_input
    for hwmon in /sys/class/hwmon/hwmon*; do
        temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
        if [[ -n "$temp" ]]; then
            echo $((temp / 1000))
            return
        fi
    done
}

get_gpu_temp() {
    # NVIDIA
    if command -v nvidia-smi &>/dev/null; then
        temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ -n "$temp" ]]; then
            echo "$temp"
            return
        fi
    fi
    # AMD (amdgpu via hwmon)
    for hwmon in /sys/class/hwmon/hwmon*; do
        name=$(cat "$hwmon/name" 2>/dev/null)
        if [[ "$name" == "amdgpu" ]]; then
            temp=$(cat "$hwmon/temp1_input" 2>/dev/null)
            if [[ -n "$temp" ]]; then
                echo $((temp / 1000))
                return
            fi
        fi
    done
}

cpu=$(get_cpu_temp)
gpu=$(get_gpu_temp)

# Determine max temp for display
if [[ -n "$cpu" && -n "$gpu" ]]; then
    if (( cpu >= gpu )); then max=$cpu; else max=$gpu; fi
    tooltip="CPU: ${cpu}°C | GPU: ${gpu}°C"
elif [[ -n "$cpu" ]]; then
    max=$cpu
    tooltip="CPU: ${cpu}°C"
elif [[ -n "$gpu" ]]; then
    max=$gpu
    tooltip="GPU: ${gpu}°C"
else
    printf '{"text": "%s N/A %s", "tooltip": "No temperature sensors found", "class": "normal"}\n' "$ICON" "$SEP"
    exit 0
fi

if (( max >= CRIT )); then
    icon=$ICON_CRIT
    class="critical"
else
    icon=$ICON
    class="normal"
fi

printf '{"text": "%s %s°C %s", "tooltip": "%s", "class": "%s"}\n' "$icon" "$max" "$SEP" "$tooltip" "$class"
""";
    }
}
