namespace ThemeEngine.Generators;

public class WallpaperSwitchGenerator : IGenerator
{
    public string Name => "Wallpaper Switch";
    public string OutputPath => ".config/hypr/scripts/wallpaper-switch.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var imageEntries = string.Join("\n", theme.Wallpapers.Images.Select(i => $"  \"$WALLPAPER_DIR/{i}\""));
        var videoEntries = string.Join("\n", theme.Wallpapers.Videos.Select(v => $"  \"$WALLPAPER_DIR/{v}\""));

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# Switches to a random wallpaper (image or video) immediately.

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"
FIT_MODE="{{theme.Wallpapers.FitMode}}"

IMAGES=(
{{imageEntries}}
)

VIDEOS=(
{{videoEntries}}
)

# Build list of valid entries based on available tools
ENTRIES=()
if command -v hyprpaper &>/dev/null; then
    for img in "${IMAGES[@]}"; do
        ENTRIES+=("image:$img")
    done
fi
if command -v mpvpaper &>/dev/null; then
    for vid in "${VIDEOS[@]}"; do
        ENTRIES+=("video:$vid")
    done
fi

if [[ ${#ENTRIES[@]} -eq 0 ]]; then
    notify-send "Wallpaper Switch" "No wallpaper tools available (hyprpaper/mpvpaper)" 2>/dev/null || true
    exit 0
fi

PICK="${ENTRIES[$((RANDOM % ${#ENTRIES[@]}))]}"
TYPE="${PICK%%:*}"
FILE="${PICK#*:}"

if [[ "$TYPE" == "video" ]]; then
    killall hyprpaper 2>/dev/null || true
    killall mpvpaper 2>/dev/null || true
    sleep 0.3
    monitors=$(hyprctl monitors -j | jq -r '.[].name')
    for mon in $monitors; do
        mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$FILE" &
    done
else
    if pgrep -x mpvpaper > /dev/null; then
        killall mpvpaper 2>/dev/null || true
        sleep 0.3
    fi
    if ! pgrep -x hyprpaper > /dev/null; then
        cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by ThemeEngine
wallpaper {
    monitor =
    path = $FILE
    fit_mode = $FIT_MODE
}

splash = false
ipc = true
HYPR
        hyprpaper &
        sleep 0.5
    fi
    hyprctl hyprpaper wallpaper ",$FILE,$FIT_MODE" 2>/dev/null || true
fi
""";
    }
}
