namespace ThemeEngine.Generators;

public class WallpaperCyclerGenerator : IGenerator
{
    public string Name => "Wallpaper Cycler";
    public string OutputPath => ".config/hypr/scripts/wallpaper-cycler.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var images = theme.Wallpapers.Images;
        var imageEntries = string.Join("\n", images.Select(i => $"  \"$WALLPAPER_DIR/{i}\""));

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# Cycles wallpapers from the theme's image list
# Usage: wallpaper-cycler.sh [interval_seconds]
# Default interval: 300 (5 minutes)

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"
INTERVAL="${1:-300}"

IMAGES=(
{{imageEntries}}
)

# Only cycle if there are multiple images
if [[ ${#IMAGES[@]} -le 1 ]]; then
    exit 0
fi

while true; do
    PICK="${IMAGES[$((RANDOM % ${#IMAGES[@]}))]}"

    # Update wallpaper via hyprctl IPC
    hyprctl hyprpaper wallpaper ",$PICK,{{theme.Wallpapers.FitMode}}" 2>/dev/null || true

    sleep "$INTERVAL"
done
""";
    }
}
