namespace ThemeEngine.Generators;

public class WallpaperCyclerGenerator : IGenerator
{
    public string Name => "Wallpaper Cycler";
    public string OutputPath => ".config/hypr/scripts/wallpaper-cycler.sh";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var imageEntries = string.Join("\n", theme.Wallpapers.Images.Select(i => $"  \"$WALLPAPER_DIR/{i}\""));
        var videoEntries = string.Join("\n", theme.Wallpapers.Videos.Select(v => $"  \"$WALLPAPER_DIR/{v}\""));

        return $$"""
#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: {{theme.Name}}
# Cycles wallpapers (images and videos) from the theme's wallpaper lists
# Usage: wallpaper-cycler.sh [interval_seconds]
# Default interval: {{theme.Wallpapers.CycleInterval}} seconds

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"
INTERVAL="${1:-{{theme.Wallpapers.CycleInterval}}}"
FIT_MODE="{{theme.Wallpapers.FitMode}}"

IMAGES=(
{{imageEntries}}
)

VIDEOS=(
{{videoEntries}}
)

# Build list of valid entries based on available tools
ENTRIES=()
if command -v hyprpaper &>/dev/null; then
    for img in "${IMAGES[@]}"; do
        ENTRIES+=("image:$img")
    done
fi
if command -v mpvpaper &>/dev/null; then
    for vid in "${VIDEOS[@]}"; do
        ENTRIES+=("video:$vid")
    done
fi

# Only cycle if there are multiple entries
if [[ ${#ENTRIES[@]} -le 1 ]]; then
    exit 0
fi

apply_wallpaper() {
    local entry="$1"
    local type="${entry%%:*}"
    local file="${entry#*:}"

    if [[ "$type" == "video" ]]; then
        killall hyprpaper 2>/dev/null || true
        killall mpvpaper 2>/dev/null || true
        sleep 0.3
        local monitors
        monitors=$(hyprctl monitors -j | jq -r '.[].name')
        for mon in $monitors; do
            mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$file" &
        done
    else
        if pgrep -x mpvpaper > /dev/null; then
            killall mpvpaper 2>/dev/null || true
            sleep 0.3
        fi
        if ! pgrep -x hyprpaper > /dev/null; then
            cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by ThemeEngine
wallpaper {
    monitor =
    path = $file
    fit_mode = $FIT_MODE
}

splash = false
ipc = true
HYPR
            hyprpaper &
            sleep 0.5
        fi
        hyprctl hyprpaper wallpaper ",$file,$FIT_MODE" 2>/dev/null || true
    fi
}

while true; do
    PICK="${ENTRIES[$((RANDOM % ${#ENTRIES[@]}))]}"
    apply_wallpaper "$PICK"
    sleep "$INTERVAL"
done
""";
    }
}
