using System.Globalization;
using System.Text.Json;

namespace ThemeEngine.Generators;

public class WaybarConfigGenerator : IGenerator
{
  public string Name => "Waybar Config";
  public string OutputPath => ".config/waybar/config.jsonc";

  public string Generate(Theme theme, string wallpapersDir)
  {
    var w = theme.Waybar;
    var c = theme.Colors;
    var labels = w.WorkspaceLabels;

    // Build format-icons object
    var iconEntries = new List<string>();
    for (var i = 0; i < labels.Length; i++)
      iconEntries.Add($"      \"{i + 1}\": \"{labels[i]}\"");
    var formatIcons = string.Join(",\n", iconEntries);

    return $$"""
            // Auto-generated by ThemeEngine — do not edit manually
            // Theme: {{theme.Name}}
            {
              "layer": "top",
              "height": {{w.Height}},
              "spacing": 0,

              "hyprland/workspaces": {
                "format": "{icon}",
                "on-click": "activate",
                "format-icons": {
            {{formatIcons}}
                }
              },

              "hyprland/window": {
                "max-length": 40,
                "separate-outputs": true
              },

              "modules-left": [
                "hyprland/workspaces",
                "hyprland/submap"
              ],

              "modules-center": [
                "clock"
              ],

              "modules-right": [
                "custom/recording",
                "pulseaudio",
                "network",
                "custom/bluetooth",
                "cpu",
                "memory",
                "custom/gpu",
                "disk",
                "temperature",
                "backlight",
                "battery",
                "power-profiles-daemon",
                "tray",
                "custom/updates",
                "custom/power"
              ],

              "custom/bluetooth": {
                "exec": "~/.config/hypr/scripts/bluetooth-status.sh",
                "return-type": "json",
                "interval": 5,
                "on-click": "kitty --title bluetuith --override background_opacity=0.95 -e bluetuith",
                "tooltip": true
              },

              "custom/updates": {
                "exec": "~/.config/hypr/scripts/update-check.sh",
                "return-type": "json",
                "interval": 600,
                "signal": 8,
                "on-click": "kitty --title updates --override background_opacity=0.95 -e bash -c 'if command -v paru &>/dev/null; then paru -Syu; elif command -v yay &>/dev/null; then yay -Syu; else sudo pacman -Syu; fi; echo; echo Done. Press enter to close.; read; pkill -RTMIN+8 waybar'",
                "tooltip": true
              },

              "clock": {
                "format": "\uf017 {:%H:%M  {{w.Separator}}  %a, %b %d}",
                "tooltip-format": "<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
                "format-alt": "\uf017 {:%Y-%m-%d  %H:%M:%S}"
              },

              "cpu": {
                "format": "\uf2db {usage}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "tooltip": true,
                "interval": 2
              },

              "memory": {
                "format": "\uf233 {}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>"
              },

              "custom/gpu": {
                "exec": "~/.config/hypr/scripts/gpu-usage.sh",
                "return-type": "json",
                "interval": 5,
                "tooltip": true
              },

              "disk": {
                "format": "\uf0a0 {percentage_used}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "tooltip-format": "{used} / {total} on {path}",
                "path": "/",
                "interval": 30
              },

              "temperature": {
                "critical-threshold": 80,
                "format": "\uf2c9 {temperatureC}\u00b0C <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-critical": "\uf2c7 {temperatureC}\u00b0C <span color='{{c.Accent1}}'>{{w.Separator}}</span>"
              },

              "backlight": {
                "format": "\uf185 {percent}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>"
              },

              "battery": {
                "states": {
                  "warning": 30,
                  "critical": 15
                },
                "format": "\uf240 {capacity}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-full": "\uf240 {capacity}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-charging": "\uf0e7 {capacity}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-plugged": "\uf1e6 {capacity}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-alt": "\uf240 {time} <span color='{{c.Accent1}}'>{{w.Separator}}</span>"
              },

              "power-profiles-daemon": {
                "format": "\uf0e7 <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "tooltip-format": "Power profile: {profile}\nDriver: {driver}",
                "tooltip": true
              },

              "network": {
                "format-wifi": "\uf1eb {essid} <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-ethernet": "\uf0e8 {ipaddr} <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "tooltip-format": "{ifname} via {gwaddr}\n{ipaddr}/{cidr}",
                "format-linked": "\uf0e8 {ifname} <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-disconnected": "\uf071 Offline <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "on-click": "kitty --title nmtui --override background_opacity=0.95 -e nmtui"
              },

              "pulseaudio": {
                "format": "\uf028 {volume}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "scroll-step": 2,
                "format-bluetooth": "\uf294 {volume}% <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-bluetooth-muted": "\uf294 muted <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "format-muted": "\uf026 muted <span color='{{c.Accent1}}'>{{w.Separator}}</span>",
                "on-click": "kitty --title pulsemixer --override background_opacity=0.95 -e pulsemixer"
              },

              "tray": {
                "icon-size": 16,
                "spacing": 8
              },

              "custom/recording": {
                "exec": "~/.config/hypr/scripts/recording-status.sh",
                "return-type": "json",
                "interval": "once",
                "signal": 9,
                "tooltip": true
              },

              "custom/power": {
                "format": "\uf011",
                "tooltip": false,
                "on-click": "~/.config/hypr/scripts/power-menu.sh"
              }
            }
            """;
  }
}
