using System.Globalization;

namespace ThemeEngine.Generators;

public class WaybarStyleGenerator : IGenerator
{
    public string Name => "Waybar Style";
    public string OutputPath => ".config/waybar/style.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var p = PaletteResolver.Resolve(theme);
        var w = theme.Waybar;
        var f = theme.Font;
        var inv = CultureInfo.InvariantCulture;

        var fontFamily = $"\"{f.Family}\", " + string.Join(", ", f.Fallback.Select(fb => fb.Contains(' ') ? $"\"{fb}\"" : fb));
        var bg0Rgba = ColorHelper.ToCssRgba(c.Bg0, w.Opacity);
        var borderRgba = ColorHelper.ToCssRgba(p.Border, 0.6);

        return $$"""
            /* Auto-generated by ThemeEngine — do not edit manually */
            /* Theme: {{theme.Name}} */

            * {
                font-family: {{fontFamily}};
                font-size: {{f.Size}}px;
            }

            window#waybar {
                background-color: {{bg0Rgba}};
                border-bottom: {{w.BorderWidth}}px solid {{borderRgba}};
                color: {{p.Text}};
                transition-property: background-color;
                transition-duration: 0.4s;
            }

            window#waybar.hidden {
                opacity: 0.2;
            }

            /* ---- Buttons / General ---- */

            button {
                box-shadow: inset 0 -2px transparent;
                border: none;
                border-radius: 0;
            }

            button:hover {
                background: inherit;
                box-shadow: inset 0 -2px {{p.Border}};
            }

            /* ---- Workspaces ---- */

            #workspaces button {
                padding: 0 6px;
                background-color: transparent;
                color: {{p.TextDim}};
                font-weight: bold;
                font-size: 11px;
            }

            #workspaces button:hover {
                background: {{ColorHelper.ToCssRgba(p.Border, 0.12)}};
                color: {{p.Text}};
            }

            #workspaces button.active {
                background-color: {{ColorHelper.ToCssRgba(p.Border, 0.18)}};
                color: {{p.Accent1}};
                box-shadow: inset 0 -2px {{p.Border}};
            }

            #workspaces button.urgent {
                background-color: {{ColorHelper.ToCssRgba(p.Red, 0.4)}};
                color: {{p.Text}};
            }

            /* ---- All modules base ---- */

            #clock,
            #battery,
            #cpu,
            #memory,
            #disk,
            #custom-temperature,
            #backlight,
            #network,
            #pulseaudio,
            #wireplumber,
            #custom-media,
            #tray,
            #mode,
            #idle_inhibitor,
            #scratchpad,
            #power-profiles-daemon,
            #custom-power {
                padding: 0 8px;
                color: {{p.Text}};
                background-color: transparent;
            }

            /* Uniform module sizing */
            #cpu,
            #memory,
            #disk,
            #custom-temperature,
            #backlight,
            #network,
            #pulseaudio,
            #battery,
            #power-profiles-daemon,
            #custom-gpu,
            #custom-bluetooth,
            #custom-updates,
            #custom-power {
                padding: 0 4px;
                min-width: 20px;
            }

            #window,
            #workspaces {
                margin: 0 4px;
            }

            .modules-left > widget:first-child > #workspaces {
                margin-left: 0;
            }

            .modules-right > widget:last-child > #workspaces {
                margin-right: 0;
            }

            /* ---- Clock ---- */

            #clock {
                font-weight: bold;
                font-size: {{f.Size}}px;
                color: {{p.TextDim}};
                padding: 0 16px;
            }

            #clock:hover {
                color: {{p.Accent1}};
            }

            /* ---- Battery ---- */

            #battery {
                color: {{p.Text}};
            }

            #battery.charging, #battery.plugged {
                color: {{p.Green}};
            }

            @keyframes blink-scarlet {
                to {
                    background-color: {{ColorHelper.ToCssRgba(p.Red, 0.5)}};
                    color: {{p.Text}};
                }
            }

            #battery.critical:not(.charging) {
                background-color: {{ColorHelper.ToCssRgba(p.Red, 0.25)}};
                color: {{p.Text}};
                animation-name: blink-scarlet;
                animation-duration: 0.8s;
                animation-timing-function: steps(12);
                animation-iteration-count: infinite;
                animation-direction: alternate;
            }

            #battery.warning {
                color: {{p.Accent2}};
            }

            /* ---- Power Profiles ---- */

            #power-profiles-daemon { color: {{p.TextDim}}; }
            #power-profiles-daemon.performance { color: {{p.Red}}; }
            #power-profiles-daemon.balanced { color: {{p.TextDim}}; }
            #power-profiles-daemon.power-saver { color: {{p.Green}}; }

            /* ---- CPU / Memory / Temperature / Backlight / Network ---- */

            #cpu { color: {{p.TextDim}}; }
            #memory { color: {{p.TextDim}}; }
            #custom-temperature { color: {{p.TextDim}}; }
            #custom-temperature.critical { color: {{p.Red}}; }
            #backlight { color: {{p.TextDim}}; }
            #network { color: {{p.TextDim}}; }
            #network.disconnected { color: {{p.Red}}; }

            /* ---- Hover brightening for all modules ---- */

            #network:hover,
            #pulseaudio:hover,
            #cpu:hover,
            #memory:hover,
            #disk:hover,
            #custom-temperature:hover,
            #custom-temperature:hover *,
            #backlight:hover,
            #battery:hover,
            #power-profiles-daemon:hover,
            #custom-power:hover,
            #custom-power:hover *,
            #custom-bluetooth:hover,
            #custom-bluetooth:hover *,
            #custom-bluetooth.connected:hover,
            #custom-bluetooth.connected:hover *,
            #custom-bluetooth.on:hover,
            #custom-bluetooth.on:hover *,
            #custom-bluetooth.off:hover,
            #custom-bluetooth.off:hover *,
            #custom-updates:hover,
            #custom-updates:hover *,
            #custom-updates.pending:hover,
            #custom-updates.pending:hover *,
            #custom-gpu:hover,
            #custom-gpu:hover * {
                color: {{p.Accent1}};
            }

            /* ---- GPU ---- */

            #custom-gpu { color: {{p.TextDim}}; }

            /* ---- Bluetooth ---- */

            #custom-bluetooth { color: {{p.TextDim}}; }
            #custom-bluetooth.connected { color: {{p.TextDim}}; }
            #custom-bluetooth.off { color: {{p.Inactive}}; }

            /* ---- Updates ---- */

            #custom-updates { color: {{p.TextDim}}; }
            #custom-updates.pending { color: {{p.Accent1}}; }
            #custom-updates.updated { color: {{p.Inactive}}; }
            #disk { color: {{p.TextDim}}; }

            /* ---- Pulseaudio ---- */

            #pulseaudio {
                color: {{p.TextDim}};
            }

            #pulseaudio.muted {
                color: {{p.Inactive}};
            }

            /* ---- Tray ---- */

            #tray {
                padding: 0 6px;
            }

            #tray > .passive {
                -gtk-icon-effect: dim;
            }

            #tray > .needs-attention {
                -gtk-icon-effect: highlight;
                background-color: {{ColorHelper.ToCssRgba(p.Red, 0.3)}};
            }

            /* ---- Power ---- */

            #custom-power {
                color: {{p.TextDim}};
                padding: 0 10px 0 6px;
            }

            #custom-power:hover {
                color: {{p.Red}};
            }

            /* ---- Recording indicator ---- */

            #custom-recording {
                color: {{p.Red}};
                font-weight: bold;
                padding: 0 6px;
                animation: blink-recording 1s steps(2) infinite;
            }

            #custom-recording.off {
                color: transparent;
                animation: none;
                padding: 0;
                margin: 0;
                min-width: 0;
            }

            @keyframes blink-recording {
                50% { opacity: 0.3; }
            }

            /* ---- Idle inhibitor ---- */

            #idle_inhibitor { color: {{p.Inactive}}; }
            #idle_inhibitor.activated { color: {{p.Accent1}}; }

            /* ---- Submap ---- */

            #submap {
                color: {{p.Accent2}};
                font-weight: bold;
            }

            /* ---- Tooltip ---- */

            tooltip {
                background-color: {{ColorHelper.ToCssRgba(c.Bg1, 0.95)}};
                border: 1px solid {{ColorHelper.ToCssRgba(p.Border, 0.5)}};
                border-radius: 4px;
                color: {{p.Text}};
            }

            tooltip label {
                color: {{p.Text}};
            }
            """;
    }
}
