namespace ThemeEngine.Generators;

public class WofiStyleGenerator : IGenerator
{
    public string Name => "Wofi Style";
    public string OutputPath => ".config/wofi/style.css";

    public string Generate(Theme theme, string wallpapersDir)
    {
        var c = theme.Colors;
        var f = theme.Font;

        return $$"""
/* Auto-generated by ThemeEngine — do not edit manually */
/* Theme: {{theme.Name}} */

window {
    margin: 0;
    border: 2px solid {{c.Border}};
    border-radius: 8px;
    background-color: {{c.Bg0}};
    font-family: "{{f.Family}}";
    font-size: 14px;
}

#input {
    margin: 8px;
    padding: 8px 12px;
    border: none;
    border-bottom: 2px solid {{c.Bg2}};
    border-radius: 4px;
    background-color: {{c.Bg1}};
    color: {{c.Text}};
    font-size: 14px;
}

#input:focus {
    border-bottom-color: {{c.Border}};
}

#inner-box {
    margin: 4px;
}

#outer-box {
    margin: 0;
    padding: 0;
}

#scroll {
    margin: 0;
}

#text {
    margin: 0;
    padding: 6px 12px;
    color: {{c.Text}};
    background: transparent;
    min-width: 100%;
}

#entry {
    padding: 0;
    margin: 2px 4px;
    border-radius: 4px;
    background: transparent;
}

#entry * {
    background: transparent;
}

#entry:selected,
#entry:selected * {
    background-color: {{c.Bg2}};
}

#entry:selected:active,
#entry:selected:active * {
    background-color: {{ColorHelper.ToCssRgba(c.Border, 0.25)}};
}

#entry:selected #text,
#entry:selected:active #text {
    color: {{c.Accent1}};
    font-weight: bold;
}
""";
    }
}
