#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: Elden Ring
# Auto-detected GPU usage for waybar

ICON=$'\uf26c'
SEP="<span color='#D4AF37'>◆</span>"

get_nvidia() {
    if command -v nvidia-smi &>/dev/null; then
        usage=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits 2>/dev/null | head -1 | tr -d ' ')
        if [[ -n "$usage" ]]; then
            printf '{"text": "%s %s%% %s", "tooltip": "NVIDIA GPU: %s%%", "class": "nvidia"}\n' "$ICON" "$usage" "$SEP" "$usage"
            return 0
        fi
    fi
    return 1
}

get_amd() {
    for gpu in /sys/class/drm/card*/device/gpu_busy_percent; do
        if [[ -r "$gpu" ]]; then
            usage=$(cat "$gpu" 2>/dev/null)
            if [[ -n "$usage" ]]; then
                printf '{"text": "%s %s%% %s", "tooltip": "AMD GPU: %s%%", "class": "amd"}\n' "$ICON" "$usage" "$SEP" "$usage"
                return 0
            fi
        fi
    done
    return 1
}

get_nvidia || get_amd || printf '{"text": "%s N/A %s", "tooltip": "No GPU detected", "class": "none"}\n' "$ICON" "$SEP"