#!/usr/bin/env bash
# Auto-generated by ThemeEngine — do not edit manually
# Theme: Elden Ring
# Toggle between static (hyprpaper) and animated (mpvpaper) wallpaper.

set -euo pipefail

WALLPAPER_DIR="$HOME/.config/hypr/wallpapers"

VIDEOS=(

)

IMAGES=(
  "$WALLPAPER_DIR/elden-ring/er-01.png"
  "$WALLPAPER_DIR/elden-ring/er-02.jpg"
)

pick_random() {
    local arr=("$@")
    echo "${arr[$((RANDOM % ${#arr[@]}))]}"
}

if pgrep -x mpvpaper > /dev/null; then
    # mpvpaper running → switch to static
    killall mpvpaper
    sleep 0.3

    IMAGE=$(pick_random "${IMAGES[@]}")
    cat > "$HOME/.config/hypr/hyprpaper.conf" <<HYPR
# Auto-generated by ThemeEngine
wallpaper {
    monitor =
    path = $IMAGE
    fit_mode = cover
}

splash = false
ipc = true
HYPR
    hyprpaper &
elif pgrep -x hyprpaper > /dev/null; then
    # hyprpaper running → switch to animated
    if ! command -v mpvpaper &> /dev/null; then
        notify-send "mpvpaper not installed" "Install mpvpaper from AUR to use animated wallpapers" 2>/dev/null || true
        exit 0
    fi
    killall hyprpaper 2>/dev/null || true
    sleep 0.3
    VIDEO=$(pick_random "${VIDEOS[@]}")
    monitors=$(hyprctl monitors -j | jq -r '.[].name')
    for mon in $monitors; do
        mpvpaper -o "no-audio loop hwdec=auto" "$mon" "$VIDEO" &
    done
else
    # Nothing running → start hyprpaper
    hyprpaper &
fi