-- #######################################################################################
-- HYPRLAND CONFIG (Lua).
-- Migrated from hyprland.conf — hyprlang is deprecated since Hyprland 0.55.
-- Refer to the wiki: https://wiki.hypr.land/Configuring/Start/
-- #######################################################################################

-- Configuration is split across multiple files, pulled in with require().
-- NOTE: a bare require() of a missing file is a hard error that aborts the rest of
-- this config, so every generated/machine-local file is loaded through pcall below.

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Machine-specific monitor config lives in monitors.lua (not tracked in git,
-- generated by quick-visor). Optional: fall back to Hyprland's autodetection.
if not pcall(require, "monitors") then
	hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end

-- Theme generated by Rainbeau (not tracked in git). Without it Hyprland just
-- uses its built-in defaults, so a missing theme is non-fatal.
pcall(require, "theme")

-- XWayland scaling - render at native res, let Hyprland scale
hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "kitty"
local fileManager = "nautilus"
-- omni-shell hosts the launcher (it instantiates OmniLauncher.Launcher), so the
-- toggle goes to omni-shell's IPC rather than the standalone omni-launcher
-- daemon — running both would put two launchers on screen.
local menu = "omni-shell-ipc launcher toggle"
local shell = "omni-shell-ipc"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)

	-- omni-shell replaces waybar (bar), dunst (notification daemon), the wofi power
	-- menu (Control Center) and the standalone omni-launcher daemon.
	hl.exec_cmd("omni-shell & hyprpaper & firefox")

	-- Cycle wallpapers periodically (5 min default, only if multiple images in theme)
	hl.exec_cmd("~/.config/hypr/scripts/wallpaper-cycler.sh 300")

	-- Launch hyprlock on startup as login screen (works with SDDM autologin)
	hl.exec_cmd("hyprlock")

	-- Start AND auto-unlock gnome-keyring-daemon (intune-portal /
	-- microsoft-identity-broker require a password-protected keyring;
	-- SDDM autologin can't unlock it via PAM).
	-- Password is read from ~/.config/hypr/.keyring-pwd (mode 0600).
	hl.exec_cmd("~/.config/hypr/scripts/unlock-keyring.sh")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Custom XDG data dirs for repo-managed desktop entries.
-- The list below is rewritten by linux/init-desktop-entries.sh — keep it on one line.
local repoDataDirs = { "shell-dev-general", "shell-dev-work" }

local home = os.getenv("HOME")
local dataDirs = {}
for _, dir in ipairs(repoDataDirs) do
	dataDirs[#dataDirs + 1] = home .. "/.local/share/" .. dir
end
dataDirs[#dataDirs + 1] = home .. "/.local/share"
dataDirs[#dataDirs + 1] = "/usr/local/share"
dataDirs[#dataDirs + 1] = "/usr/share"

hl.env("XDG_DATA_DIRS", table.concat(dataDirs, ":"))

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied
-- on-the-fly for security reasons

-- hl.config({ ecosystem = { enforce_permissions = true } })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Theme-managed settings (general, decoration, animations, misc) are in theme.lua
-- Only layout and non-theme settings remain here

hl.config({
	-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
	dwindle = {
		preserve_split = true,
		smart_split = true,
	},

	-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
	master = {
		new_status = "master",
	},
})

---------------
---- INPUT ----
---------------

-- https://wiki.hypr.land/Configuring/Basics/Variables/#input
hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
		},
	},
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(
	mainMod .. " + M",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo()) -- dwindle
hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle

-- Control Center — power actions (lock/sleep/log off/restart/shutdown), Wi-Fi,
-- Bluetooth, VPN, DND, power profile, volume and brightness. Replaces the wofi
-- power menu that used to be bound here.
hl.bind(mainMod .. " + X", hl.dsp.exec_cmd(shell .. " control toggle"))
hl.bind(mainMod .. " + ALT + P", hl.dsp.exec_cmd(shell .. " control toggle"))

-- Clipboard history
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.exec_cmd(shell .. " clipboard toggle"))

-- Weather panel
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(shell .. " weather toggle"))

-- Do Not Disturb
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd(shell .. " control dnd"))

-- Theme picker (was reachable from the wofi power menu)
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("rainbeau select --themes-dir ~/.config/rainbeau/themes/"))

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Move active window to another monitor
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ monitor = "-1" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ monitor = "+1" }))

-- Fullscreen toggle
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen())

-- Take screenshot of region
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd('grim -g "$(slurp)" - | wl-copy'))

-- Toggle screen recording (start/stop, saves to ~/Documents/Recordings)
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("~/.config/hypr/scripts/screen-record.sh"))

-- Switch to a random wallpaper (image or video)
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-switch.sh"))

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Lid switch: disable laptop screen when lid closes, re-enable when it opens
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("~/.config/hypr/lid-switch.sh close"), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("~/.config/hypr/lid-switch.sh open"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})

------------------
----  LAYERS  ----
------------------

-- Backdrop blur for the omni-shell surfaces (bar, notification centre, control
-- centre, launcher, toasts). ignore_alpha masks the blur to non-transparent
-- pixels, so the gaps between bar sections and the rounded corners stay sharp —
-- an unmasked blur rule blurs the whole surface bounding box instead.
hl.layer_rule({
	name = "omni-shell-blur",
	match = { namespace = "^(quickshell)$" },

	blur = true,
	ignore_alpha = 0,
})
