-- Auto-generated by ThemeEngine — do not edit manually
-- Theme: Elden Ring
return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = true,
    opts = {
      flavour = "mocha",
      integrations = { lsp = true, treesitter = true },
      color_overrides = {
        mocha = {
          base = "#0B0B0F",
          mantle = "#1A1610",
          crust = "#0B0B0F",
          surface0 = "#2B2420",
          surface1 = "#3D3530",
          surface2 = "#4A4035",
          overlay0 = "#A89070",
          overlay1 = "#A89070",
          overlay2 = "#C8A84E",
          text = "#E8D5B5",
          subtext0 = "#A89070",
          subtext1 = "#A89070",
          lavender = "#D4AF37",
          blue = "#4A6A7A",
          sapphire = "#4A6A7A",
          sky = "#C8A84E",
          teal = "#5A7247",
          green = "#5A7247",
          yellow = "#D4AF37",
          peach = "#B5722A",
          maroon = "#8B2500",
          red = "#8B2500",
          mauve = "#C8A84E",
          pink = "#B5722A",
          flamingo = "#D4AF37",
          rosewater = "#E8D5B5",
        },
      },
      custom_highlights = function(colors)
        return {
          ["@lsp.type.interface.cs"] = {
            fg = colors.sky,
            style = { "bold", "italic" },
          },
          ["@lsp.type.class.cs"] = {
            fg = colors.lavender,
            style = {},
          },
          ["@lsp.type.extensionMethodName.cs"] = {
            fg = colors.mauve,
            style = { "bold" },
          },
          ["@lsp.type.variable.cs"] = {
            fg = colors.text,
            style = { "italic" },
          },
          ["@lsp.type.staticField.cs"] = {
            fg = colors.peach,
            style = { "bold" },
          },
        }
      end,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = { colorscheme = "catppuccin" },
  },
}